server:
  address: ${LISTEN_ADDRESS:127.0.0.1}
  port: ${LISTEN_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:storage1c}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
    hibernate:
      ddl-auto: validate

  mvc:
    log-resolved-exception: true

  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB

storage1c:
  file-locking:
    enabled: false
  security:
    remember-me-key: ${REMEMBER_ME_KEY:15bd8d60-e818-4ecf-8cbf-c29bdc73189b}
  git:
    root: ${GIT_ROOT_PATH:/opt/repos/}
    file-download-url: ${FILE_DOWNLOAD_URL:http://127.0.0.1:8080/api/v1/repos/%d/blobs/%s?fname=%s}
    zip-download-url: ${ZIP_DOWNLOAD_URL:http://127.0.0.1:8080/api/v1/repos/%d/cfzip/%s?fname=%s}
    file-download-key: ${FILE_DOWNLOAD_KEY:ce1cc7e6-e611-4577-8439-0512de1ddf83}
  unpack:
    root: ${UNPACK_ROOT_PATH:/tmp}
    v8unpack-path: ${V8UNPACK_PATH:v8unpack}
