spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:storage1c}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
    hibernate:
      ddl-auto: validate

  mvc:
    log-resolved-exception: true

  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

storage1c:
  security:
    remember-me-key: ${REMEMBER_ME_KEY:15bd8d60-e818-4ecf-8cbf-c29bdc73189b}
